### ISSUE TITLE
Serial Manager RPMsg implementation has only prototypes

### ISSUE THREAD

**Issue by kmeinhar** [varigit/freertos-variscite#1]
The Serial Manager has the option to be configured to type [`kSerialPort_Rpmsg`](https://github.com/varigit/freertos-variscite/blob/mcuxpresso_sdk_2.10.x-var01/components/serial_manager/fsl_component_serial_manager.h#L335).
But has far as I can tell all functions related to it are only prototypes with no implementation (e.g. [Serial_RpmsgInit](https://github.com/varigit/freertos-variscite/blob/mcuxpresso_sdk_2.10.x-var01/components/serial_manager/fsl_component_serial_port_internal.h#L56))

Is there an implementation for it that I missed and if not is there a plan to create one?

**Comment by FrancescoFerraro** [comment]
Hi @kmeinhar
You are right
The Serial Manager has the option to be configured to type [kSerialPort_Rpmsg] but NXP provide only prototypes with no implementation.
Variscite has no plans to implement the rpmsg serial,  for dedicated support should contact the sales department at sales@variscite.com.

Thanks
BR
Francesco
